version: "3"
services:
    web:	
        image: sparkwebapp:2.0
        deploy:
            replicas: 20
            resources:
                limits:
                    cpus: "0.15"
                    memory: 100M
            restart_policy:
                condition: on-failure
        ports:
            - "8080:4567"
        networks:
            - webnet
networks:
    webnet:
